# Q1. Pandas version

In [1]:
import pandas as pd
pd.__version__

'2.2.3'

# Q2. Records count

In [3]:
df = pd.read_csv("laptops.csv")
df.head(n=2)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0

In [6]:
len(df)

2160

# Q3. Laptops brands

In [13]:
df.Brand.nunique()
# len(df.Brand.unique())

27

# Q4. Missing values

In [17]:
missing_sum = df.isnull().sum()
len(missing_sum[missing_sum > 0])

3

# Q5. Maximum final price

In [21]:
int(df[df.Brand == "Dell"]["Final Price"].max())

3936

# Q6. Median value of Screen

In [24]:
# Find the median
df.Screen.median()

np.float64(15.6)

In [30]:
# Find the most frecuent
df.Screen.mode()[0]
# df.Screen.value_counts()

np.float64(15.6)

In [31]:
df.Screen.fillna(15.6)

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [32]:
# Find the median again
df.Screen.median()

np.float64(15.6)

# Q7. Sum of weights

In [51]:
# Select all the "Innjoo" laptops from the dataset.
# Select only columns RAM, Storage, Screen.
# Get the underlying NumPy array. Let's call it X.
x = df[df.Brand == 'Innjoo'][['RAM', 'Storage', 'Screen']].values
x

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [55]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
xtx = x.T.dot(x)
xtx

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [59]:
# Compute the inverse of XTX.
import numpy as np
xtxi = np.linalg.inv(xtx)
xtxi

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [62]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = xtxi.dot(x.T).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [66]:
# What's the sum of all the elements of the result?
w.sum().round(2)

np.float64(91.3)